-- =============================================
-- TABLA: requerimientos
-- Ejecuta esto DESPUÉS de haber corrido supabase_setup.sql
-- =============================================

-- Descomenta solo en entorno de prueba si necesitas re-ejecutar:
-- drop view if exists milestone_rf_summary;
-- drop table if exists requerimientos cascade;

create table requerimientos (
  id               serial primary key,
  codigo           text not null unique,
  nombre           text not null,
  estado           text not null default 'Pendiente',
  milestone_id     integer references milestones(id),
  milestone_codigo text
);

insert into requerimientos (codigo, nombre, estado, milestone_codigo) values
('RF01', 'Consultar en dashboard Turnos', 'Pendiente', 'M7'),
('RF02', 'Consultar en dashboard SIARA', 'Pendiente', 'M7'),
('RF03', 'Consultar en dashboard Emplazamientos', 'Pendiente', 'M7'),
('RF04', 'Consultar en dashboard Ejecuciones', 'Pendiente', 'M7'),
('RF05', 'Consultar módulos', 'Pendiente', 'M7'),
('RF06', 'Agregar módulo', 'Pendiente', 'M7'),
('RF07', 'Editar módulo', 'Pendiente', 'M7'),
('RF08', 'Eliminar módulo', 'Pendiente', 'M7'),
('RF09', 'Ver detalle de módulo', 'Pendiente', 'M7'),
('RF10', 'Consultar los registros de un módulo', 'Pendiente', 'M7'),
('RF11', 'Crear un registro', 'Pendiente', 'M7'),
('RF12', 'Editar un registro', 'Pendiente', 'M7'),
('RF13', 'Eliminar un registro', 'Pendiente', 'M7'),
('RF14', 'Buscar con filtros', 'Pendiente', 'M7'),
('RF15', 'Consultar filtros', 'Pendiente', 'M7'),
('RF16', 'Crear filtros', 'Pendiente', 'M7'),
('RF17', 'Eliminar filtro', 'Pendiente', 'M7'),
('RF18', 'Editar columna', 'Pendiente', 'M7'),
('RF19', 'Eliminar columna', 'Pendiente', 'M7'),
('RF20', 'Consultar en dashboard Mis Tareas', 'Pendiente', 'M7'),
('RF21', 'Consultar en dashboard Agenda', 'Pendiente', 'M7'),
('RF22', 'Consultar en dashboard Juicios', 'Pendiente', 'M7'),
('RF23', 'Encabezado y navegación principal', 'Pendiente', 'M2'),
('RF24', 'Consultar recordatorios en Dashboard', 'Pendiente', 'M7'),
('RF25', 'Crear Tarea', 'Pendiente', 'M3'),
('RF26', 'Consultar tareas', 'Pendiente', 'M3'),
('RF27', 'Cambiar el estado de una tarea', 'Pendiente', 'M3'),
('RF28', 'Consultar domicilios de un juicio', 'Pendiente', 'M5'),
('RF29', 'Agregar domicilio a un juicio', 'Pendiente', 'M5'),
('RF30', 'Editar domicilio de un juicio', 'Pendiente', 'M5'),
('RF31', 'Eliminar domicilio de un juicio', 'Pendiente', 'M5'),
('RF32', 'Crear carpetas', 'Pendiente', 'M4'),
('RF33', 'Abrir archivo en el visualizador de archivos', 'Pendiente', 'M4'),
('RF34', 'Consultar detalle de carpeta', 'Pendiente', 'M4'),
('RF35', 'Renombrar carpeta', 'Pendiente', 'M4'),
('RF36', 'Eliminar carpeta', 'Pendiente', 'M4'),
('RF37', 'Consultar información de un archivo', 'Pendiente', 'M4'),
('RF38', 'Editar información de un archivo', 'Pendiente', 'M4'),
('RF39', 'Consultar archivos y carpetas por nivel', 'Pendiente', 'M4'),
('RF40', 'Mover archivos a otro nivel', 'Pendiente', 'M4'),
('RF41', 'Eliminar archivo', 'Pendiente', 'M4'),
('RF42', 'Cargar archivos al sistema', 'Pendiente', 'M4'),
('RF43', 'Cambio de estado desde el modal de edición', 'Pendiente', 'M3'),
('RF44', 'Eliminar tarea', 'Pendiente', 'M3'),
('RF45', 'Reasignar tareas', 'Pendiente', 'M3'),
('RF46', 'Paso 1: Información General', 'Pendiente', 'M5'),
('RF47', 'Consultar agenda', 'Pendiente', 'M3'),
('RF48', 'Paso 2: Partes', 'Pendiente', 'M5'),
('RF49', 'Detección automática de juicios sin movimiento', 'Pendiente', 'M6'),
('RF50', 'Configurar umbral de días sin movimiento', 'Pendiente', 'M6'),
('RF51', 'Consultar en dashboard Tarjetas de resumen', 'Pendiente', 'M7'),
('RF52', 'Paso 3: Documentos', 'Pendiente', 'M5'),
('RF53', 'Consultar timeline de juicio', 'Pendiente', 'M7'),
('RF54', 'Registro automático de eventos en el timeline', 'Pendiente', 'M7'),
('RF55', 'Registrar evento manual en el timeline', 'Pendiente', 'M7'),
('RF56', 'Crear subcategorías de garantías', 'Pendiente', 'M4'),
('RF57', 'Editar subcategoría de garantía', 'Pendiente', 'M4'),
('RF58', 'Eliminar subcategoría de garantía', 'Pendiente', 'M4'),
('RF59', 'Editar evento del timeline', 'Pendiente', 'M7'),
('RF60', 'Eliminar evento del timeline', 'Pendiente', 'M7'),
('RF61', 'Paso 4: Garantías', 'Pendiente', 'M5'),
('RF62', 'Paso 5: Domicilios', 'Pendiente', 'M5'),
('RF63', 'Extraer campos de un formato de dictamen', 'Pendiente', 'M8'),
('RF64', 'Crear formulario de dictamen a partir de campos extraídos', 'Pendiente', 'M8'),
('RF65', 'Preparar documento plantilla para formato de dictamen', 'Pendiente', 'M8'),
('RF66', 'Crear comentario en un juicio', 'Pendiente', 'M7'),
('RF67', 'Eliminar comentario en un juicio', 'Pendiente', 'M7'),
('RF68', 'Consultar comentarios del juicio', 'Pendiente', 'M7'),
('RF69', 'Editar comentario en un juicio', 'Pendiente', 'M7'),
('RF70', 'Crear nuevo juicio', 'Pendiente', 'M5'),
('RF71', 'Sugerir etapas de juicio', 'Pendiente', 'M5'),
('RF72', 'Consultar etapas de juicio', 'Pendiente', 'M5'),
('RF73', 'Cambiar etapa de juicio', 'Pendiente', 'M5'),
('RF74', 'Consultar tareas de etapa', 'Pendiente', 'M5'),
('RF75', 'Crear etapa en sugerir etapa', 'Pendiente', 'M5'),
('RF76', 'Consultar fecha de última modificación de un juicio', 'Pendiente', 'M5'),
('RF77', 'Consultar detalle de juicio', 'Pendiente', 'M5'),
('RF78', 'Consultar lista de juicios', 'Pendiente', 'M5'),
('RF79', 'Modificar detalle de juicio', 'Pendiente', 'M5'),
('RF80', 'Cambiar estado de juicio', 'Pendiente', 'M5'),
('RF81', 'Consultar colaboradores', 'Pendiente', 'M5'),
('RF82', 'Gestionar colaboradores de un juicio', 'Pendiente', 'M5'),
('RF83', 'Paso 7: Resumen', 'Pendiente', 'M5'),
('RF84', 'Cargar juicios masivamente', 'Pendiente', 'M9'),
('RF85', 'Cargar juicio', 'Pendiente', 'M9'),
('RF86', 'Buscar y asociar documento existente a un juicio', 'Pendiente', 'M5'),
('RF87', 'Vaciar papelera', 'Pendiente', 'M9'),
('RF88', 'Agregar columna', 'Pendiente', 'M7'),
('RF89', 'Registrar fecha de término estimado de la etapa actual', 'Pendiente', NULL),
('RF90', 'Reordenar avances de juicio', 'Pendiente', 'M5'),
('RF91', 'Consultar bitácora de avances del juicio', 'Pendiente', 'M5'),
('RF92', 'Agregar avance a la bitácora de avances', 'Pendiente', 'M5'),
('RF93', 'Editar avance en la bitácora de avances', 'Pendiente', 'M5'),
('RF94', 'Eliminar avance de la bitácora de avances', 'Pendiente', 'M5'),
('RF95', 'Filtrar avances en la bitácora de avances', 'Pendiente', 'M5'),
('RF96', 'Agregar juicio a Dashboard', 'Pendiente', 'M9'),
('RF97', 'Consultar documentos de juicio', 'Pendiente', 'M5'),
('RF98', 'Crear solicitud de cambio en un juicio', 'Pendiente', 'M8'),
('RF99', 'Consultar solicitudes de cambio de un juicio', 'Pendiente', 'M8'),
('RF100', 'Resolver solicitud de cambio de un juicio', 'Pendiente', 'M8'),
('RF101', 'Consultar información de etapas pasadas del juicio', 'Pendiente', NULL),
('RF102', 'Registrar garantia', 'Pendiente', 'M4'),
('RF103', 'Modificar garantía', 'Pendiente', 'M4'),
('RF104', 'Consultar garantías por juicio', 'Pendiente', 'M4'),
('RF105', 'Consultar detalle de garantía', 'Pendiente', 'M4'),
('RF106', 'Eliminar garantía', 'Pendiente', 'M4'),
('RF107', 'Importar catálogo a categoría de garantía', 'Pendiente', 'M4'),
('RF108', 'Crear categorías de garantías', 'Pendiente', 'M4'),
('RF109', 'Consultar categorías y subcategorías de garantía', 'Pendiente', 'M4'),
('RF110', 'Editar categoria de garantía', 'Pendiente', 'M4'),
('RF111', 'Eliminar categoría de garantía', 'Pendiente', 'M4'),
('RF112', 'Crear catalogo', 'Pendiente', 'M2'),
('RF113', 'Consultar catálogos', 'Pendiente', 'M2'),
('RF114', 'Consultar detalle de catálogo', 'Pendiente', 'M2'),
('RF115', 'Icono de eliminar para eliminar el catálogo', 'Pendiente', 'M2'),
('RF116', 'Eliminar catalogo', 'Pendiente', 'M2'),
('RF117', 'Icono de editar para editar el catálogo', 'Pendiente', 'M2'),
('RF118', 'Consultar columnas de catalogo', 'Pendiente', 'M2'),
('RF119', 'Validar campos obligatorios en catálogo', 'Pendiente', 'M2'),
('RF120', 'Archivar columna de catálogo', 'Pendiente', 'M2'),
('RF121', 'Importar registros de catálogo como opciones de un selector', 'Pendiente', 'M2'),
('RF122', 'Consultar detalle de columna', 'Pendiente', 'M2'),
('RF123', 'Modificar columna de catálogo', 'Pendiente', 'M2'),
('RF124', 'Consultar lista de registros de catálogo', 'Pendiente', 'M2'),
('RF125', 'Consultar detalle de registro de catálogo', 'Pendiente', 'M2'),
('RF126', 'Editar elemento de catálogo', 'Pendiente', 'M2'),
('RF127', 'Eliminar elemento de catálogo', 'Pendiente', 'M2'),
('RF128', 'Filtrar y buscar elementos', 'Pendiente', 'M2'),
('RF129', 'Crear nuevos usuarios del sistema', 'Pendiente', 'M2'),
('RF130', 'Consultar usuarios', 'Pendiente', 'M2'),
('RF131', 'Modificar información de usuarios', 'Pendiente', 'M2'),
('RF132', 'Borrar usuario', 'Pendiente', 'M2'),
('RF133', 'Consultar perfil de usuario', 'Pendiente', 'M2'),
('RF134', 'Iniciar sesión con proveedor externo (SSO)', 'Pendiente', 'M2'),
('RF135', 'Cerrar sesión', 'Pendiente', 'M2'),
('RF136', 'Recuperar contraseña', 'Pendiente', 'M2'),
('RF137', 'Cambiar contraseña', 'Pendiente', 'M2'),
('RF138', 'Modificar rol de usuario', 'Pendiente', 'M2'),
('RF139', 'Crear nuevo rol', 'Pendiente', 'M2'),
('RF140', 'Acceder mediante magic link', 'Pendiente', 'M2'),
('RF141', 'Completar perfil', 'Pendiente', 'M2'),
('RF142', 'Consultar permisos por rol', 'Pendiente', 'M2'),
('RF143', 'Modificar permisos de un rol', 'Pendiente', 'M2'),
('RF144', 'Modificar rol', 'Pendiente', 'M2'),
('RF145', 'Eliminar rol', 'Pendiente', 'M2'),
('RF146', 'Consultar roles', 'Pendiente', 'M2'),
('RF147', 'Consultar detalle de permiso', 'Pendiente', 'M2'),
('RF148', 'Consultar permisos', 'Pendiente', 'M2'),
('RF149', 'Consultar roles no asociados', 'Pendiente', 'M2'),
('RF150', 'Consultar rol', 'Pendiente', 'M2'),
('RF151', 'Mapear y crear registros desde el sistema actual', 'Pendiente', 'M10'),
('RF152', 'Validar integridad de datos migrados', 'Pendiente', 'M10'),
('RF153', 'Resolver conflictos de datos', 'Pendiente', 'M10'),
('RF154', 'Reasignar contenido de un usuario', 'Pendiente', 'M2'),
('RF155', 'Consultar información del despacho', 'Pendiente', 'M2'),
('RF156', 'Editar datos del despacho', 'Pendiente', 'M2'),
('RF157', 'Eliminar o desactivar sede', 'Pendiente', 'M2'),
('RF158', 'Registrar nueva sede del despacho', 'Pendiente', 'M2'),
('RF159', 'Consultar sede del despacho', 'Pendiente', 'M2'),
('RF160', 'Editar sede del despacho', 'Pendiente', 'M2'),
('RF161', 'Consultar usuarios por sede', 'Pendiente', 'M2'),
('RF162', 'Reasignar sede a usuario', 'Pendiente', 'M2'),
('RF163', 'Buscar en toda la plataforma', 'Pendiente', 'M9'),
('RF164', 'Crear cliente', 'Pendiente', 'M3'),
('RF165', 'Consultar clientes', 'Pendiente', 'M3'),
('RF166', 'Consultar cliente', 'Pendiente', 'M3'),
('RF168', 'Consultar recordatorios (vista principal)', 'Pendiente', 'M6'),
('RF169', 'Filtrar tareas', 'Pendiente', NULL),
('RF170', 'Crear recordatorio', 'Pendiente', 'M6'),
('RF171', 'Editar recordatorio', 'Pendiente', 'M6'),
('RF172', 'Completar recordatorio', 'Pendiente', 'M6'),
('RF173', 'Consultar notificaciones (vista principal)', 'Pendiente', 'M6'),
('RF174', 'Editar cliente', 'Pendiente', NULL),
('RF175', 'Eliminar cliente', 'Pendiente', NULL),
('RF176', 'Vaciar bandeja de notificaciones', 'Pendiente', NULL),
('RF177', 'Consultar expediente de cliente', 'Pendiente', NULL),
('RF178', 'Agregar documento a favoritos', 'Pendiente', NULL),
('RF179', 'Consultar dashboard de juicios sin avance +60 días', 'Pendiente', NULL),
('RF180', 'Consultar información de la etapa actual del juicio', 'Pendiente', NULL),
('RF181', 'Alerta sin movimiento +60 en juicio', 'Pendiente', NULL),
('RF182', 'Generar bitácora de documento', 'Pendiente', 'M9'),
('RF183', 'Consultar papelera de reciclaje de documentos', 'Pendiente', 'M9'),
('RF184', 'Enviar documentos a papelera de reciclaje', 'Pendiente', 'M9'),
('RF185', 'Recuperar documentos desde la papelera de reciclaje', 'Pendiente', 'M9'),
('RF186', 'Descargar tabla', 'Pendiente', 'M9'),
('RF187', 'Descargar archivo', 'Pendiente', 'M4'),
('RF188', 'REUSAR', 'Pendiente', NULL),
('RF189', 'Iniciar chat colaborativo por juicio', 'Pendiente', 'M8'),
('RF190', 'Crear mensaje en chat', 'Pendiente', 'M8'),
('RF191', 'Enviar mensaje en chat', 'Pendiente', 'M8'),
('RF192', 'Tarjeta Timeline', 'Pendiente', 'M8'),
('RF193', 'Consultar detalle de chat', 'Pendiente', 'M8'),
('RF194', 'Adjuntar archivos dentro del chat del juicio', 'Pendiente', 'M8'),
('RF195', 'Descargar archivos enviados en el chat', 'Pendiente', 'M8'),
('RF196', 'Enviar notificaciones de chat', 'Pendiente', 'M8'),
('RF197', 'Búsqueda de juicios con filtros', 'Pendiente', NULL),
('RF198', 'Consultar filtros personalizados por usuario', 'Pendiente', NULL),
('RF199', 'Modificar filtros personalizados por usuario', 'Pendiente', NULL),
('RF200', 'Guardar filtros personalizados', 'Pendiente', NULL),
('RF201', 'Generar dictámenes con datos del juicio', 'Pendiente', 'M8'),
('RF202', 'Al hacer clic en una tarea: redirigir a vista', 'Pendiente', 'M5'),
('RF203', 'Consultar dictámenes generados', 'Pendiente', 'M8'),
('RF204', 'Eliminar dictamen generado', 'Pendiente', 'M8'),
('RF205', 'Crear formato de dictamen', 'Pendiente', 'M8'),
('RF206', 'Editar formato de dictamen', 'Pendiente', 'M8'),
('RF207', 'Eliminar formato de dictamen', 'Pendiente', 'M8'),
('RF208', 'Consultar formato de dictamen', 'Pendiente', 'M8'),
('RF209', 'Seleccionar formato de dictamen', 'Pendiente', 'M8'),
('RF210', 'Consultar detalle de dictamen', 'Pendiente', 'M8'),
('RF211', 'Consultar formatos existentes para dictamen', 'Pendiente', 'M8'),
('RF212', 'Crear comentario en un documento', 'Pendiente', 'M9'),
('RF213', 'Editar contenido de un comentario', 'Pendiente', 'M9'),
('RF214', 'Eliminar comentario en un documento', 'Pendiente', 'M9'),
('RF215', 'Consultar comentarios en un documento', 'Pendiente', 'M9'),
('RF216', 'Consultar bitácora de documentos', 'Pendiente', 'M9'),
('RF217', 'Duplicar archivo', 'Pendiente', 'M4'),
('RF218', 'Consultar campos de formulario de cliente', 'Pendiente', NULL),
('RF219', 'Actualizar campos de formulario de cliente', 'Pendiente', NULL),
('RF220', 'Usar datos del formulario de cliente para cargar en un Juicio', 'Pendiente', NULL),
('RF225', 'Modificar información de usuario', 'Pendiente', 'M2'),
('RF226', 'Consultar perfil de usuario', 'Pendiente', 'M2'),
('RF227', 'Editar mensaje en chat', 'Pendiente', 'M8'),
('RF228', 'Eliminar mensaje en chat', 'Pendiente', 'M8'),
('RF231', 'Configurar catálogo fuente de un selector', 'Pendiente', NULL),
('RF237', 'Cambiar el tipo de una tarea', 'Pendiente', 'M3'),
('RF242', 'Cargar carpetas al sistema', 'Pendiente', 'M4'),
('RF260', 'DEPRECADO', 'Pendiente', 'M3'),
('RF267', 'Crear columna de Kanban Tareas', 'Pendiente', 'M3'),
('RF268', 'Editar header de columna Kanban', 'Pendiente', 'M3'),
('RF269', 'Eliminar columna Kanban', 'Pendiente', 'M3'),
('RF270', 'Pop-up acceso rápido a Crear tarea', 'Pendiente', 'M3'),
('RF340', 'Dividir vista (max 2)', 'Pendiente', 'M4'),
('RF341', 'Gestionar presets de filtros de tareas', 'Pendiente', 'M9'),
('RF342', 'Buscar, filtrar y gestionar presets de juicios', 'Pendiente', 'M9'),
('RF343', 'Filtrar garantías', 'Pendiente', 'M9'),
('RF344', 'Filtrar archivos en el centro de archivos', 'Pendiente', 'M9'),
('RF345', 'Filtrar clientes', 'Pendiente', 'M9'),
('RF962', 'Enviar notificaciones por correo', 'Pendiente', 'M6'),
('RF990', 'Consultar notificaciones en panel lateral del dashboard', 'Pendiente', 'M6'),
('RF998', 'Mencionar a un usuario', 'Pendiente', 'M8'),
('RF-AN-01', 'Dashboard de métricas generales', 'Pendiente', 'M4'),
('RF-AN-02', 'Métricas de juicios por etapa', 'Pendiente', 'M4'),
('RF-AN-03', 'Métricas de actividad del equipo', 'Pendiente', 'M4'),
('RF-AN-04', 'Métricas de garantías', 'Pendiente', 'M4'),
('RF-AN-05', 'Métricas de clientes', 'Pendiente', 'M4'),
('RF-AN-06', 'Métricas de tareas', 'Pendiente', 'M4'),
('RF-AN-07', 'Exportar métricas', 'Pendiente', 'M4');

-- Vincular con milestone_id
update requerimientos r
set milestone_id = m.id
from milestones m
where r.milestone_codigo = m.codigo;

create index if not exists idx_requerimientos_milestone_id on requerimientos(milestone_id);

-- RLS: solo lectura pública
alter table requerimientos enable row level security;
create policy "Lectura pública RFs" on requerimientos for select using (true);

-- =============================================
-- Vista: resumen de RFs por milestone
-- =============================================
create or replace view milestone_rf_summary as
select
  m.id,
  m.codigo,
  m.nombre,
  m.estado as milestone_estado,
  count(r.id)                                                        as total_rfs,
  count(r.id) filter (where r.estado = 'Completado')               as rfs_completados,
  count(r.id) filter (where r.estado = 'En progreso')              as rfs_en_progreso,
  count(r.id) filter (where r.estado = 'Atrasado')                 as rfs_atrasados,
  count(r.id) filter (where r.estado = 'Bloqueado')                as rfs_bloqueados,
  count(r.id) filter (where r.estado = 'Nuevo')                    as rfs_nuevos,
  count(r.id) filter (where r.estado = 'Pendiente')                as rfs_pendientes
from milestones m
left join requerimientos r on r.milestone_id = m.id
group by m.id, m.codigo, m.nombre, m.estado
order by m.id;

grant select on milestone_rf_summary to anon;

-- =============================================
-- Estados válidos para requerimientos:
--   Pendiente | En progreso | Completado | Atrasado | Bloqueado | Nuevo
-- Para actualizar un RF:
--   update requerimientos set estado = 'Completado' where codigo = 'RF25';
-- =============================================
